version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '5'
  driver: json-file

services:
  ccw:
    image: "naturalis/ccw:0.0.2"
    restart: unless-stopped
    env_file:
      - .env
    ports:
     - "8080:80"
    volumes:
      - "${BASE_PATH:-/data}/www:/var/www/html"
      - "${BASE_PATH:-/data}/ccw:/data"
      - "${BASE_PATH:-/data}/apachelogs:/var/log/apache2"
    logging: *default-logging
    networks:
      - default
    labels:
      - "traefik.backend=ccw"
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.port=80"
      - ${CCW_URL_CONFIG:-traefik.frontend.rule=Host:ccw.naturalis.nl}

  db:
    image: "mysql:5"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-blablabla}
      MYSQL_DATABASE: ${MYSQL_DB:-ccw}
      MYSQL_USER: ${MYSQL_USER:-ccw_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-blablabla}
    logging: *default-logging
    networks:
      - default
    volumes:
    - "./mysqlconfig:/etc/mysql/conf.d"
    - "${BASE_PATH:-/data}/mysqllog:/var/log/mysql"
    - "${BASE_PATH:-/data}/db:/var/lib/mysql"

  minio:
    image: "minio/minio"
    restart: unless-stopped
    command: "server /data"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-12345}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-12345678}
    logging: *default-logging
    ports:
      - "9000:9000"
    volumes: 
      - "${BASE_PATH:-/data}/miniodata:/data"
      - "${BASE_PATH:-/data}/minioconfif:/root/.minio"
    networks:
      - default
    labels:
      - "traefik.backend=minio"
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.port=9000"
      - ${MINIO_URL_CONFIG:-traefik.frontend.rule=Host:ccw-storage.naturalis.nl}

  traefik:
    image: traefik:1.7.12
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8081:8080
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${TRAEFIK_TOML_FILE:-./traefik/traefik.toml}:/traefik.toml
      - ${CERTDIR:-/etc/letsencrypt}:/etc/letsencrypt
    logging: *default-logging


# run docker network create web before
networks:
  web:
    external: true

